### ISSUE TITLE
Install and run issues

### ISSUE THREAD

**Issue by simonh1000** [thomasstreet/famous-angular-starter#4]
Super excited about this.....

Have just enough background knowledge to see that I needed to install bower and npm files, and worked out that I also needed gulp installed globally.  Then figured out that I needed `gulp serve`, but in the chrome browser control panel I keep getting 
`Failed to load resource: net::ERR_CONNECTION_REFUSED http://localhost:35729/livereload.js?snipver=1` and thats blocking all real functionality.

`gulp serve:dist` just gets loads of files unavailable messages

**Comment by musictray** [comment]
It appears that bower is not installing jquery, underscore or livereload in the correct directory.

I did `bower install jquery`, `bower install underscore` and `bower install liverload` by hand, and got rid of all but the livereload error:

`Failed to load resource: net::ERR_CONNECTION_REFUSED  http://localhost:35729/livereload.js?snipver=1`

when `gulp serve` is entered

**Comment by zackbrown** [comment]
Hey guys—thanks for reporting this stuff.  The bower.json and package.json are both updated now, as is the README with clearer instructions.  I just tested it with a fresh clone and it seems good to go.

All you should have to do now is `npm install` (first time) and then run `gulp watch` (instead of gulp serve)

I built this off of the generator-gulp-angular npm package, which seems to have some rough edges (like gulp serve apparently not starting the auto-reloader,) but it's otherwise pretty solid.

**Comment by musictray** [comment]
Much better thanks. However, I still had to run a `bower install` and `bower install jquery` and `bower install underscore` separately before `gulp watch` worked.

I also had a problem in the npm install, but I think that's a sudo issue associated with connect.

**Comment by zackbrown** [comment]
As configured, it _should_ run `bower install` automatically after a successful `npm install` (see scripts.install inside of package.json) —but if you're having issues with `npm install` that may never be getting run.  Both jQuery and Underscore are listed as dependencies in bower.json, so they should also be getting installed from a simple `bower install`.

When I tried these steps from a fresh clone, everything worked for me—is it possible these issues are specific to your current environment?

**Comment by musictray** [comment]
Yes, it is an absolute possibility. It's a new iMac, and I'm just getting things set up on it, so it maybe something I've screwed up. I'll check it out tonight, and let you know.

And yes, I saw jquery and underscore in bower.json, and I couldn't figure it out myself.

Thanks for your quick response.

**Comment by musictray** [comment]
Yup. I uninstalled-reinstalled node. Works fine now. Thanks.

**Comment by simonh1000** [comment]
Sadly, even after a clean install and I ended up with Browser errors:

`TypeError: undefined is not a function
    at Object.enter (http://localhost:9000/bower_components/angular-animate/angular-animate.js:553:16)
    at Object.enter (http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:2667:57)
    at http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:2734:22
    at publicLinkFn (http://localhost:9000/bower_components/angular/angular.js:5890:29)
    at updateView (http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:2733:23)
    at http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:2703:9
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:6579:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:5982:15)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:5989:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:5989:13) `

and in the terminal:

`Started connect web server on http://localhost:9000
[gulp] Live reload server listening on: 35729
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.`

**Comment by zackbrown** [comment]
Good catch @simonh1000: this error was due a bug that we just allowed to sneak past in our famous-angular 0.0.13 release this evening (appropriately unlucky, I guess?)  I just pushed out a patch with 0.0.14, and tested again with another fresh clone here.  Looks to be working again.

**Comment by simonh1000** [comment]
OK, so it installed and loaded, but nothing happened when I clicked on the 'hello famous' surface in the centre of the screen (and I have one small surface half way off the screen in the top left corner).  I can see how the aim is to use Transitionable's to cause one of the surfaces to scale up, but they don't seem to be running and that's meaning the opacity transition is not happening either.

Meanwhile, I started playing around git checkout 0, 1, .. and quickly found myself with code where famo.us itself was missing, i.e. `<script type="text/javascript" src="//code.famo.us/famous/0.2.0/famous.min.js"></script>` is missing

**Comment by zackbrown** [comment]
The first part is expected behavior:  on master, nothing will happen with you click 'hello famous.'  There is supposed to be some behavior as you step through the tags, but I'll address this in #5 

The part about the famous CDN script missing is also expected; F/A currently doesn't use the CDN'd Famo.us script; it uses AMD to load the scripts from the bower_components/famous folder.  In fact, we will probably be using a concatenated Famo.us script soon, as soon as Famous supports a method for accessing all of the global objects in a hash without using AMD.  See https://github.com/Famous/famous-angular/issues/57 —but the short story is, for F/A there should not be a `<script type="text/javascript" src="//code.famo.us/famous/0.2.0/famous.min.js"></script>` anywhere on the page.
